export const tourData = [
	{
		id: 1,
		city: 'Eivissa',
		img: '../image/ibiza.jpg',
		name: 'Dalt Villa Tour',
		info: 'Ibiza (en catalán y oficialmente Eivissa) es una isla española situada en el mar Mediterráneo y que forma junto a las de Mallorca, Menorca y Formentera y varios islotes de menor tamaño el archipiélago y comunidad autónoma de las Islas Baleares.',
	},
	{
		id: 2,
		city: 'Sant Antoni de Portmany',
		img: '../image/san-antonio.jpg',
		name: 'San Antonio lights tour',
		info: 'San Antonio Abad (en catalán y oficialmente Sant Antoni de Portmany) es una parroquia y un municipio español de la isla de Ibiza, en la comunidad autónoma de Islas Baleares, España. Situado en el oeste de la isla, su territorio corresponde a parte de lo que fue el antiguo cuartón de Portmany, uno de los cuatro en que el Rey Jaime I dividió la isla en siglo xiii tras conquistarla para la Corona de Aragón en 1235.',
	},
	{
		id: 3,
		city: 'Santa Eulalia',
		img: '../image/santae.jpg',
		name: 'Santa Eulalia royal palace tour',
		info: 'Santa Eulalia del Río (en ibicenco y oficialmente Santa Eulària des Riu, en catalán Santa Eulàlia del Riu) es un municipio de la comunidad autónoma de las Islas Baleares (España). Situado en la parte oriental de la isla de Ibiza. En la época musulmana la zona se llamaba Xarc.',
	},
	{
		id: 4,
		city: 'Portinatx',
		img: '../image/portinatax.jpg',
		name: 'portinatx ibiza sushi tour',
		info: 'La playa Cala Portinatx está situada en San Juan Bautista, en la parte norte de la isla de Ibiza, en la Comunidad Autónoma de las Islas Baleares, España.',
	},
	{
		id: 5,
		city: 'Sant Josep de sa talaia',
		img: '../image/ibiza-sant-josep-de-sa-talaia_121.jpg',
		name: 'Sant Josep de sa talaia tour',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel,repellendus!',
	},
	{
		id: 6,
		city: 'Cala Llonga',
		img: '../image/calalonga.jpg',
		name: 'Cala Llonga blue tour',
		info: 'La playa Cala Llonga está situada en Santa Eulalia del Río, en la parte oriental de la isla de Ibiza, en la Comunidad Autónoma de las Islas Baleares, España.',
	},
	{
		id: 7,
		city: 'San Vincente',
		img: '../image/cala-san-vicente-ibiza.jpg',
		name: 'San Vincente Happy Hipee tour',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel,repellendus!',
	},
];
