export const tourData = [
	{
		id: 1,
		city: 'Eivissa',
		img: '../image/ibiza.jpg',
		name: 'Dalt Villa Tour',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel,repellendus!',
	},
	{
		id: 2,
		city: 'Sant Antoni de Portmany',
		img: '../image/san-antonio.jpg',
		name: 'San Antonio lights tour',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel,repellendus!',
	},
	{
		id: 3,
		city: 'Santa Elalia',
		img: '../image/santae.jpg',
		name: 'Santa Elalia royal palace tour',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel,repellendus!',
	},
	{
		id: 4,
		city: 'Portinatx',
		img: '../image/portinatax.jpg',
		name: 'portinatx ibiza sushi tour',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel,repellendus!',
	},
	{
		id: 5,
		city: 'Sant Josep de sa talaia',
		img: '../image/ibiza-sant-josep-de-sa-talaia_121.jpg',
		name: 'Sant Josep de sa talaia tour',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel,repellendus!',
	},
	{
		id: 6,
		city: 'Cala Llonga',
		img: '../image/calalonga.jpg',
		name: 'Cala Llonga blue tour',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel,repellendus!',
	},
	{
		id: 7,
		city: 'San Vincente',
		img: '../image/cala-san-vicente-ibiza.jpg',
		name: 'San Vincente Happy Hipee tour',
		info: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel,repellendus!',
	},
];
